### ISSUE TITLE
Relay access denied

### ISSUE THREAD

**Issue by keomabrun** [YunoHost-Apps/mailman_ynh#12]
I am not able to send email to the list after installing the app.

```
I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<mailman@chif.fr>: host spool.mail.gandi.net[217.70.178.1] said: 554 5.7.1
    <mailman@chif.fr>: Relay access denied (in reply to RCPT TO command)
```

any suggestion ?

**Comment by alexAubin** [comment]
Hmmm can you validate that `yunohost tools regen-conf postfix` is happy and that you did not edit manually the config ?

**Comment by keomabrun** [comment]
Mew
```
admin@chif:~$ sudo yunohost tools regen-conf postfix --dry-run
admin@chif:~$
```
I promise I did not edit the config manually <3

**Comment by keomabrun** [comment]
Hm. Looks like none of my email adresses works actually. Forget about it. I just haven't configure the dns zone .... :cry:

**Comment by keomabrun** [comment]
Works now. Sorry for the noise.
![SHAME](http://giphygifs.s3.amazonaws.com/media/jUwpNzg9IcyrK/giphy.gif)
