### ISSUE TITLE
Semi-public/private application ?

### ISSUE THREAD

**Issue by drousset** [YunoHost-Apps/mailman_ynh#13]
Hi,
I use mailman v2 from yunohost without major problem.
Users can subscribe without being a yunohost server know user. This is the public side !
As soon as a user wants to authenticate in order to manage its subscription, he needs to provide a yunohost user/password information.

How can I fix that and give users the right to manage their subscription ?

Thanks
D.

**Comment by alexAubin** [comment]
Should be fixed from the recent testing, sorry about that
