### ISSUE TITLE
mailman won't work after install

### ISSUE THREAD

**Issue by Ternoc** [YunoHost-Apps/mailman_ynh#36]
After initial install, mailman won't work and show this error page
<img width="1440" alt="Capture d’écran 2021-11-21 à 06 07 01" src="https://user-images.githubusercontent.com/11840322/142750376-9bf545e6-fa02-4857-8dc8-8ee513d7055a.png">

Yunohost version : 4.3.3

**Comment by Ternoc** [comment]
When accessing to services pannel in Yunohost, it shows that the mailman status is X auto restart.

There is the logs : 

[mailman.txt](https://github.com/YunoHost-Apps/mailman_ynh/files/7657538/mailman.txt)

**Comment by Aeris1One** [comment]
Same, seems to be since either commit 289bf408d57bf564d6cdaa9324b4f0152eee379a or Yunohost 4.3 release

**Comment by Aeris1One** [comment]
Sooo... Here's my log gathering plan :
1. rm /var/log/mailman
2. Install Yunohost app
3. Wait 5 mins
4. Upload content of /var/log/error and /var/log/qrunner

Install logs : https://paste.yunohost.org/raw/mirojuxibu
/var/log/error : https://paste.yunohost.org/raw/okibetodef
/var/log/qrunner : https://paste.yunohost.org/raw/faqiyepevo

**Comment by Aeris1One** [comment]
Well, seems it's not related to 4.3 release as I thought, but may well be related to a commit, because when package_check checks "upgrading from old commit" it works at least for a second... So, commit 3b980e7a46de9861d178d92d18f6f6dd269c93c8 works...
